CC=gcc
CFLAGS=-std=c99 -Wall -c -Wc++-compat -O3
LIBS=-lX11 -lGL
DEMOS=\
	DeepOpacity \
	Raycast \

SHARED=glew.o pez.o bstrlib.o pez.linux.o
PREFIX=bug-

all: $(DEMOS)

DeepOpacity: $(PREFIX)DeepOpacity.o $(PREFIX)DeepOpacity.glsl $(SHARED) Smoke96.pbo
	$(CC) $(PREFIX)$@.o $(SHARED) -o $@ $(LIBS)

Raycast: $(PREFIX)Raycast.o $(PREFIX)Raycast.glsl $(SHARED) Smoke96.pbo
	$(CC) $(PREFIX)$@.o $(SHARED) -o $@ $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o $(DEMOS)
